version: '3.9'
services:
  web:
    image: api-notification:latest
    networks:
      - schambeck-overlay
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - CUSTOM_CORS_ALLOWED_ORIGINS=http://localhost:4200
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - AUTH_URI=http://srv-authorization:9000/auth/realms/schambeck
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
  db:
    image: 'postgres:12.9-alpine'
    networks:
      - schambeck-overlay
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  schambeck-overlay:
    external: true
