version: '3.9'
services:
  web:
    image: api-notification:latest
    networks:
      schambeck-net:
        aliases:
          - api-notification
    environment:
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-notification:5432/notification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - CUSTOM_CORS_ALLOWED_ORIGINS=http://localhost:4200
      - DISCOVERY_URI=http://srv-discovery:8761/eureka
      - AUTH_URI=http://srv-authorization:9000/auth/realms/schambeck
      - SPRING_RABBITMQ_HOST=srv-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_VIRTUAL_HOST=
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.services.api-notification.loadbalancer.server.port=80
  db:
    image: 'postgres:12.9-alpine'
    networks:
      schambeck-net:
        aliases:
          - db-notification
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  schambeck-net:
    external: true
